boards/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from markdownx import urls as markdownx

app_name = 'boards'

urlpatterns = [
    path('list/', views.BoardListView.as_view(), name='board_list'),  # board_list 기본 & 목록
    path('favorite/', views.FavoriteBoardListView.as_view(), name='favorite_board_list'),
    path('new/', views.BoardCreateView.as_view(), name='board_create'),
    path('<int:pk>/', views.BoardDetailView.as_view(), name='board_detail'),
    path('<int:pk>/modifav', views.modifiy_favorite, name='modifiy_favorite'),
    path('markdownx/', include('markdownx.urls')),
    # path('<int:pk>/update/', views.BoardUpdateView.as_view(), name='board_update'),
    # path('<int:pk>/delete/', views.BoardDeleteView.as_view(), name='board_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#  MEDIA_URL로 접근하면 MEDIA_ROOT 경로에 저장된 파일을 서비스하도록 설정함. 이제 파일 업로드 뷰에서 파일을 업로드하면 MEDIA_ROOT에 파일이 저장되고, 데이터베이스에는 파일 경로가 저장됨.

common/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views  # login&logout
from . import views
from boards.views import BoardListView

app_name = 'common'

urlpatterns = [
    # path('', views.IndexView.as_view(), name='main'),
    path('', views.IndexView.as_view(template_name='boards/board_list.html')),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(template_name='common/signup.html'), name='signup'),
    path('profile/', views.profile, name='profile'),
    path('produce/', views.produce, name='produce'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls', 'common')), # '/' 에 해당되는 path
    path('', include('boards.urls', 'boards')),
]

# from django.contrib import admin
# from django.urls import path, include
# from django.conf import settings
# from django.conf.urls.static import static
# from django.views.generic.base import TemplateView
# from common import views

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     # path('', views.IndexView.as_view(), name='index'),  # '/' 에 해당되는 path
#     # path('common/', include(('common.urls', 'common'))),
#     # path('common/', include('django.contrib.auth.urls')),
#     # path('care/', include('care.urls')), # 요양원&리뷰
#     path('', include(('common.urls', 'common'))),
#     path('common/', include('django.contrib.auth.urls')),
#     path('care/', include('care.urls')), # 요양원&리뷰
#     path('care/', include('django.contrib.auth.urls')),
# ]

templates/base copy.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="{% static 'img/icons/png/autoslider_logo.png' %}" type="image/x-icon">
        <!-- google web font -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap">
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- custom CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <!-- jquery-3.6.3.min.js -->
        <script type="text/javascript" src="{% static 'js/jquery-3.6.3.min.js' %}"></script>
        <!-- bootstrap.min.js -->
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <!-- custom.js -->
        <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
        <title>AutoSlider</title>
    </head>
    <body>
        <section class="base container-fluid">
            {% if request.resolver_match.url_name is None or request.resolver_match.url_name == 'board_list' or request.resolver_match.url_name == 'favorite_board_list' and user.is_authenticated %}
            <!-- navbar -->
            {% include "navbar.html" %}
            <!-- header -->
            <header class="header">
                <h1 class="logo"><img src="{% static 'img/autoslider_logo.png' %}" alt="logo"></h1>
                <ul class="btnare">
                    <li><button id="newBoardBtn" class="btn btn-primary"><strong class="fa fa-plus" data-toggle="modal" data-target="newBoardModal">새로 만들기</strong></button></li>
                </ul>
            </header>
            {% endif%}
            <!-- 기본 템플릿 안에 삽입될 내용 Start -->
            {% block content %}
            {% endblock %}
            <!-- 기본 템플릿 안에 삽입될 내용 End -->
        </section>
        <footer class="footer bg-light">
            <div class="rows">
                <div class="rights">
                    <p class="copyright">Copyright @ AutoSlider Since 2022</p>
                </div>
                <ul class="info">
                    <li><strong>팀명 :</strong>팀_안드</li>
                    <li><strong>서비스 문의 :</strong><a href="mailto:admin@autoslider.com" class="mailto">admin@autoslider.com</a></li>
                </ul>
                <ul class="links">
                    <li><a class="btn btn-outline-light btn-floating m-1" href="https://github.com/AutoSlider/total" target="_blank" role="button"><img src="{% static 'img/icons/github-mark.png' %}" alt="gitHub linke"></a></li>
                    <li><a href="#" target="_blank"><a class="btn btn-outline-light btn-floating m-1" href="mailto:admin@autoslider.com" target="_blank" role="button"><img src="{% static 'img/icons/email.png' %}" alt="mail"></a></li>
                </ul>
            </div>
        </footer>
        <!-- 새 보드 만들기 내부 팝업 -->
        <div class="modal fade file-upload" id="newBoardModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title hide">새 보드 만들기</h4>
                        <button type="button" class="closeBoardBtn close fa fa-close" data-dismiss="modal" aria-hidden="true">
                            <strong class="modal hide">닫기</strong>
                        </button>
                    </div>
                    <form id="newBoardForm" method="post" action="">
                        {% csrf_token %}
                        <div class="modal-body">
                            <!-- select 태그 추가 -->
                            <div class="form-group select_type">
                                <label for="selectInput" class="modal">입력 방법 선택:</label>
                                <select id="selectInput" class="form-control input_type" name="input_type">
                                    <option value="input_text">텍스트 요약</option>
                                    <option value="input_youtube">Youtube 영상 링크 입력</option>
                                    <option value="input_video">영상 파일 업로드</option>
                                </select>
                            </div>
                            <div class="form-group input_text">
                                <label for="input_text" class="modal">텍스트 요약:</label>
                                <input type="text" class="form-control" id="input_text" name="input_text" placeholder="요약할 텍스트를 입력해주세요.">
                            </div>
                            <div class="form-group input_youtube">
                                <label for="input_youtube" class="modal hide">Youtube 영상 링크 입력:</label>
                                <input type="text" class="form-control" id="input_youtube" name="input_youtube" placeholder="유튜브 링크 입력하기">
                            </div>
                            <div class="form-group input_video">
                                <label for="input_video">
                                    <input type="file" class="form-control-file" id="input_video" name="input_video">
                                    <span><strong class="fa fa-plus"></strong><p>내 파일을 클릭하세요</p><p>자신이 원하는 mp4영상을 추가하세요</p></span>
                                </label>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <ul class="btnarea">
                                <li><button type="submit" class="btn btn-primary">적용하기</button></li>
                                <li><button type="button" class="btn btn-default closeBoardBtn" data-dismiss="modal" onclick="resetForm()">취소</button></li>
                            </ul>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- # newBoard JavaScript -->
        <script type="text/javascript" >
            $(document).ready(function() {
                $('#newBoardBtn').on('click', function () {
                    $('#newBoardModal').modal('show');
                });
                $('.closeBoardBtn').on('click', function () {
                    $('#newBoardModal').modal('hide');
                    $('#newBoardForm')[0].reset();
                    $('.form-group').hide();
                    $('#selectInput').val('');
                  });
                $('#selectInput').on('change', function() {
                    var selectedValue = $(this).val();
                    $('.input_' + selectedValue).show();
                    $('.form-group:not(.input_' + selectedValue + ') input, .form-group:not(.input_' + selectedValue + ') select').val('');
                    $('.form-group:not(.input_' + selectedValue + ')').hide();
                });
            });
        </script>
    </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/x-icon" href="{% static 'img/icons/favicon.ico' %}">
        <!-- google web font -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap">
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet">
        <!-- Bootstrap 5 CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous"> {% endcomment %}
        <!-- font-awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- custom CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <!-- jquery-3.6.3.min.js -->
        <script type="text/javascript" src="{% static 'js/jquery-3.6.3.min.js' %}"></script>
        {% comment %} <!-- bootstrap.min.js -->
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script> {% endcomment %}
        <!-- Bootstrap 5 js -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
        <!-- custom.js -->
        <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
        <title>AutoSlider</title>
    </head>
    <body>
        <section class="base container-fluid">
            <!-- 기본 템플릿 안에 삽입될 내용 Start -->
            {% block content %}
            {% endblock %}
            <!-- 기본 템플릿 안에 삽입될 내용 End -->
        </section>
    </body>
</html>

templates/footer.html
{% load static %}
<div id="footer_div">
    <div id="footer_font">
        <img src="{% static 'img/andlogo.jpg' %}" alt="logoimage">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <B style = "font-size:16px">CONTACT US&nbsp;&nbsp;&nbsp;</B>
        <i class="bi bi-telephone-fill">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
            </svg>
        </i><span>전화번호: 02-599-8697 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
        <i class="bi bi-house-door-fill">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-at-fill" viewBox="0 0 16 16">
                <path d="M2 2A2 2 0 0 0 .05 3.555L8 8.414l7.95-4.859A2 2 0 0 0 14 2H2Zm-2 9.8V4.698l5.803 3.546L0 11.801Zm6.761-2.97-6.57 4.026A2 2 0 0 0 2 14h6.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.606-3.446l-.367-.225L8 9.586l-1.239-.757ZM16 9.671V4.697l-5.803 3.546.338.208A4.482 4.482 0 0 1 12.5 8c1.414 0 2.675.652 3.5 1.671Z"/>
                <path d="M15.834 12.244c0 1.168-.577 2.025-1.587 2.025-.503 0-1.002-.228-1.12-.648h-.043c-.118.416-.543.643-1.015.643-.77 0-1.259-.542-1.259-1.434v-.529c0-.844.481-1.4 1.26-1.4.585 0 .87.333.953.63h.03v-.568h.905v2.19c0 .272.18.42.411.42.315 0 .639-.415.639-1.39v-.118c0-1.277-.95-2.326-2.484-2.326h-.04c-1.582 0-2.64 1.067-2.64 2.724v.157c0 1.867 1.237 2.654 2.57 2.654h.045c.507 0 .935-.07 1.18-.18v.731c-.219.1-.643.175-1.237.175h-.044C10.438 16 9 14.82 9 12.646v-.214C9 10.36 10.421 9 12.485 9h.035c2.12 0 3.314 1.43 3.314 3.034v.21Zm-4.04.21v.227c0 .586.227.8.581.8.31 0 .564-.17.564-.743v-.367c0-.516-.275-.708-.572-.708-.346 0-.573.245-.573.791Z"/>
        </svg>
        </i><a href="mailto:autoslider@site.com">관리자 이메일: autoslider@site.com &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
        <!-- 3조안드 팀소개 -->
        <a href="{% url 'common:produce' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-android" viewBox="0 0 16 16">
            <path d="M2.76 3.061a.5.5 0 0 1 .679.2l1.283 2.352A8.94 8.94 0 0 1 8 5a8.94 8.94 0 0 1 3.278.613l1.283-2.352a.5.5 0 1 1 .878.478l-1.252 2.295C14.475 7.266 16 9.477 16 12H0c0-2.523 1.525-4.734 3.813-5.966L2.56 3.74a.5.5 0 0 1 .2-.678ZM5 10a1 1 0 1 0 0-2 1 1 0 0 0 0 2Zm6 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"/>
            </svg><span>팀소개</span>
        </a>
    </div>
    <p id="footer_Copyright">Copyright ⓒ2023 And.&nbsp;All Rights Reserved.</p>
</div>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
{% load static %}
<!-- header -->
<header class="header">
  <h1 class="logo"><img src="{% static 'img/autoslider_logo.png' %}" alt="logo"></h1>
  <ul class="btnarea">
    {% if request.resolver_match.url_name is None or request.resolver_match.url_name == 'board_list' or request.resolver_match.url_name == 'favorite_board_list' %}
      <li><button id="newBoardBtn" class="btn btn-primary"><strong class="fa fa-plus" data-toggle="modal" data-target="newBoardModal"><span>새로 만들기</span></strong></button></li>
    {% endif %}
  </ul>
</header>
<!-- navbar -->
<nav class="navigation navbar navbar-nav">
    <ul class="navbar-nav">
      <li class="nav-item"><a href="{% url 'common:profile' %}">{{ user.nickname }}</a>님 안녕하세요.</li>
      <li class="nav-item"><a href="{% url 'common:logout' %}" class="btn btn-secondary">로그아웃</a></li>
      <li class="nav-item"><a href="{% url 'boards:board_list' %}" class="nav-link" >메인 보드</a></li>
      <li class="nav-item"><a href="{% url 'boards:favorite_board_list' %}" class="nav-link" >즐겨찾기</a></li>
    </ul>
</nav>

templates/tml.html
<section class="boardlist">
    {% if request.resolver_match.url_name is None or request.resolver_match.url_name == 'board_list' %}
    <h2>메인 보드</h2>
      {% if all_boards %}
        {% for board in all_boards %}
        <h3>{{ board.name }}</h3>
        <p>{{ board.description }}</p>
        <hr>
        {% endfor %}
      {% else %}
      빈 목록 - 메인보드
      {% endif %}
    {% elif request.resolver_match.url_name == 'favorite_board_list' %}
    <h2>즐겨찾기</h2>
      {% if all_boards %}
        {% for board_fav in all_boards %}
          {% if board_fav.favorite %}
          <h3>{{ board_fav.name }}</h3>
          <p>{{ board_fav.description }}</p>
          <hr>
          {% endif %}
        {% endfor %}
      {% else %}
        빈 목록 - 즐겨찾기
      {% endif %}
    {% endif %}
    </section>